modelo.Usuario=repositorios.especificos.RepositorioUsuariosAdHocJPA
modelo.Categoria=repositorios.especificos.RepositorioCategoriasAdHocJPA
modelo.Producto=repositorios.especificos.RepositorioProductosAdHocJPA
