spring.application.name=compraventas

spring.data.mongodb.uri=mongodb://root:***REMOVED***@mongo:27017/db_compraventas?authSource=admin
usuarios.base.url=http://usuarios:8080/api/
productos.base.url=http://productos:8081/
server.port=8082
