spring.application.name=compraventas

spring.data.mongodb.uri=mongodb://root:***REMOVED***@mongo:27017/db_compraventas?authSource=admin
retrofit.usuarios.baseUrl=http://usuarios:8080/api/
retrofit.productos.baseUrl=http://productos:8081/
server.port=8082

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}

jwt.secret=***REMOVED***
jwt.expiration-seconds=3600
jwt.cookie-name=jwt
