export const CATEGORIAS = [
  { id: 1, nombre: 'Electrónica' },
  { id: 2, nombre: 'Ropa y Moda' },
  { id: 3, nombre: 'Hogar y Jardín' },
  { id: 4, nombre: 'Deportes' },
  { id: 5, nombre: 'Libros y Música' },
  { id: 6, nombre: 'Juguetes y Bebé' },
  { id: 7, nombre: 'Vehículos' },
  { id: 8, nombre: 'Informática' },
];

// estado: nuevo | como_nuevo | buen_estado | aceptable | para_piezas_o_reparar
export const PRODUCTOS = [
  {
    id: 1,
    titulo: 'iPhone 13 128GB Azul',
    descripcion: 'iPhone 13 en perfecto estado. Batería al 92%. Incluye cargador original y funda.',
    precio: 550,
    estado: 'como_nuevo',
    fecha_publicacion: '2026-03-01',
    categoria_id: 1,
    num_visualizaciones: 142,
    envio_disponible: true,
    lugar_recogida: 'Murcia capital',
    vendedor_id: 2,
    imagen: 'https://picsum.photos/seed/prod1/400/300',
  },
  {
    id: 2,
    titulo: 'Samsung Galaxy S22 Negro',
    descripcion: 'Galaxy S22 con 256GB de almacenamiento. Algunas marcas en la pantalla, funciona perfectamente.',
    precio: 380,
    estado: 'buen_estado',
    fecha_publicacion: '2026-03-05',
    categoria_id: 1,
    num_visualizaciones: 89,
    envio_disponible: true,
    lugar_recogida: 'Cartagena',
    vendedor_id: 3,
    imagen: 'https://picsum.photos/seed/prod2/400/300',
  },
  {
    id: 3,
    titulo: 'MacBook Pro 14" M1 Pro',
    descripcion: 'MacBook Pro 2021 con chip M1 Pro, 16GB RAM, 512GB SSD. Impecable, sin arañazos.',
    precio: 1400,
    estado: 'como_nuevo',
    fecha_publicacion: '2026-03-08',
    categoria_id: 8,
    num_visualizaciones: 210,
    envio_disponible: false,
    lugar_recogida: 'Murcia capital',
    vendedor_id: 2,
    imagen: 'https://picsum.photos/seed/prod3/400/300',
  },
  {
    id: 4,
    titulo: 'Teclado mecánico Keychron K2',
    descripcion: 'Teclado mecánico inalámbrico con switches Brown. Layout TKL. Incluye bolsa de transporte.',
    precio: 75,
    estado: 'buen_estado',
    fecha_publicacion: '2026-03-10',
    categoria_id: 8,
    num_visualizaciones: 55,
    envio_disponible: true,
    lugar_recogida: 'Lorca',
    vendedor_id: 3,
    imagen: 'https://picsum.photos/seed/prod4/400/300',
  },
  {
    id: 5,
    titulo: 'Monitor LG 27" 4K',
    descripcion: 'Monitor LG 27UK850. Panel IPS 4K, USB-C. Un píxel muerto en esquina inferior.',
    precio: 220,
    estado: 'aceptable',
    fecha_publicacion: '2026-03-12',
    categoria_id: 8,
    num_visualizaciones: 98,
    envio_disponible: false,
    lugar_recogida: 'Murcia capital',
    vendedor_id: 2,
    imagen: 'https://picsum.photos/seed/prod5/400/300',
  },
  {
    id: 6,
    titulo: 'Chaqueta North Face talla L',
    descripcion: 'Chaqueta impermeable North Face, talla L. Muy poco uso, ideal para montaña.',
    precio: 90,
    estado: 'como_nuevo',
    fecha_publicacion: '2026-03-14',
    categoria_id: 2,
    num_visualizaciones: 44,
    envio_disponible: true,
    lugar_recogida: 'Murcia capital',
    vendedor_id: 3,
    imagen: 'https://picsum.photos/seed/prod6/400/300',
  },
  {
    id: 7,
    titulo: 'Zapatillas Nike Air Max 90 42',
    descripcion: 'Nike Air Max 90 talla 42. Usadas unas pocas veces. Sin caja original.',
    precio: 65,
    estado: 'buen_estado',
    fecha_publicacion: '2026-03-15',
    categoria_id: 2,
    num_visualizaciones: 77,
    envio_disponible: true,
    lugar_recogida: 'Cartagena',
    vendedor_id: 2,
    imagen: 'https://picsum.photos/seed/prod7/400/300',
  },
  {
    id: 8,
    titulo: 'Abrigo lana gris M',
    descripcion: 'Abrigo de lana merina, talla M. Comprado en El Corte Inglés. Excelente estado.',
    precio: 45,
    estado: 'buen_estado',
    fecha_publicacion: '2026-03-16',
    categoria_id: 2,
    num_visualizaciones: 31,
    envio_disponible: true,
    lugar_recogida: 'Murcia capital',
    vendedor_id: 3,
    imagen: 'https://picsum.photos/seed/prod8/400/300',
  },
  {
    id: 9,
    titulo: 'Sofá esquinero 3 plazas gris',
    descripcion: 'Sofá chaise longue gris marengo. 2 años de uso, sin manchas. Requiere furgoneta.',
    precio: 350,
    estado: 'buen_estado',
    fecha_publicacion: '2026-03-17',
    categoria_id: 3,
    num_visualizaciones: 120,
    envio_disponible: false,
    lugar_recogida: 'Murcia capital',
    vendedor_id: 2,
    imagen: 'https://picsum.photos/seed/prod9/400/300',
  },
  {
    id: 10,
    titulo: 'Cafetera Nespresso Vertuo',
    descripcion: 'Cafetera Nespresso Vertuo Next en color negro. Incluye 20 cápsulas de regalo.',
    precio: 55,
    estado: 'como_nuevo',
    fecha_publicacion: '2026-03-18',
    categoria_id: 3,
    num_visualizaciones: 63,
    envio_disponible: true,
    lugar_recogida: 'Cartagena',
    vendedor_id: 3,
    imagen: 'https://picsum.photos/seed/prod10/400/300',
  },
  {
    id: 11,
    titulo: 'Aspiradora Dyson V11',
    descripcion: 'Dyson V11 con todos sus accesorios. Batería dura aprox 40 minutos.',
    precio: 280,
    estado: 'buen_estado',
    fecha_publicacion: '2026-03-19',
    categoria_id: 3,
    num_visualizaciones: 88,
    envio_disponible: false,
    lugar_recogida: 'Murcia capital',
    vendedor_id: 2,
    imagen: 'https://picsum.photos/seed/prod11/400/300',
  },
  {
    id: 12,
    titulo: 'Bicicleta de montaña Trek 29"',
    descripcion: 'Trek Marlin 5 2022. Talla M. Poco uso, cadena y frenos nuevos hace 3 meses.',
    precio: 600,
    estado: 'como_nuevo',
    fecha_publicacion: '2026-03-20',
    categoria_id: 4,
    num_visualizaciones: 175,
    envio_disponible: false,
    lugar_recogida: 'Murcia capital',
    vendedor_id: 3,
    imagen: 'https://picsum.photos/seed/prod12/400/300',
  },
  {
    id: 13,
    titulo: 'Pesas ajustables 2x20kg',
    descripcion: 'Set de mancuernas ajustables de 2 a 20kg cada una. Con soporte incluido.',
    precio: 120,
    estado: 'buen_estado',
    fecha_publicacion: '2026-03-21',
    categoria_id: 4,
    num_visualizaciones: 54,
    envio_disponible: false,
    lugar_recogida: 'Lorca',
    vendedor_id: 2,
    imagen: 'https://picsum.photos/seed/prod13/400/300',
  },
  {
    id: 14,
    titulo: 'Raqueta de tenis Babolat Pure Drive',
    descripcion: 'Babolat Pure Drive 2021, grip 2. Encordada con Luxilon hace 2 meses.',
    precio: 85,
    estado: 'buen_estado',
    fecha_publicacion: '2026-03-22',
    categoria_id: 4,
    num_visualizaciones: 29,
    envio_disponible: true,
    lugar_recogida: 'Cartagena',
    vendedor_id: 3,
    imagen: 'https://picsum.photos/seed/prod14/400/300',
  },
  {
    id: 15,
    titulo: 'Lote Harry Potter 7 tomos',
    descripcion: 'Colección completa Harry Potter en tapa blanda. Edición Salamandra. Buen estado.',
    precio: 40,
    estado: 'buen_estado',
    fecha_publicacion: '2026-03-23',
    categoria_id: 5,
    num_visualizaciones: 67,
    envio_disponible: true,
    lugar_recogida: 'Murcia capital',
    vendedor_id: 2,
    imagen: 'https://picsum.photos/seed/prod15/400/300',
  },
  {
    id: 16,
    titulo: 'Guitarra acústica Yamaha F310',
    descripcion: 'Guitarra acústica para principiantes. Con funda incluida. Afinada y lista para tocar.',
    precio: 70,
    estado: 'buen_estado',
    fecha_publicacion: '2026-03-24',
    categoria_id: 5,
    num_visualizaciones: 93,
    envio_disponible: false,
    lugar_recogida: 'Murcia capital',
    vendedor_id: 3,
    imagen: 'https://picsum.photos/seed/prod16/400/300',
  },
  {
    id: 17,
    titulo: 'Vinilo Pink Floyd The Wall',
    descripcion: 'Vinilo doble The Wall de Pink Floyd. Edición original 1979. Ligero crackle.',
    precio: 25,
    estado: 'aceptable',
    fecha_publicacion: '2026-03-25',
    categoria_id: 5,
    num_visualizaciones: 38,
    envio_disponible: true,
    lugar_recogida: 'Cartagena',
    vendedor_id: 2,
    imagen: 'https://picsum.photos/seed/prod17/400/300',
  },
  {
    id: 18,
    titulo: 'LEGO Technic 42083 Bugatti',
    descripcion: 'LEGO Technic Bugatti Chiron completo, con caja e instrucciones. Montado una sola vez.',
    precio: 180,
    estado: 'como_nuevo',
    fecha_publicacion: '2026-03-26',
    categoria_id: 6,
    num_visualizaciones: 111,
    envio_disponible: true,
    lugar_recogida: 'Murcia capital',
    vendedor_id: 3,
    imagen: 'https://picsum.photos/seed/prod18/400/300',
  },
  {
    id: 19,
    titulo: 'Trona Chicco Polly Magic',
    descripcion: 'Trona evolutiva Chicco Polly Magic 2 en 1. Color naranja. Muy buen estado.',
    precio: 55,
    estado: 'buen_estado',
    fecha_publicacion: '2026-03-27',
    categoria_id: 6,
    num_visualizaciones: 42,
    envio_disponible: false,
    lugar_recogida: 'Lorca',
    vendedor_id: 2,
    imagen: 'https://picsum.photos/seed/prod19/400/300',
  },
  {
    id: 20,
    titulo: 'Patinete eléctrico Xiaomi Pro 2',
    descripcion: 'Xiaomi Mi Electric Scooter Pro 2. 300km totales. Batería al 85%.',
    precio: 320,
    estado: 'buen_estado',
    fecha_publicacion: '2026-03-28',
    categoria_id: 7,
    num_visualizaciones: 195,
    envio_disponible: false,
    lugar_recogida: 'Murcia capital',
    vendedor_id: 3,
    imagen: 'https://picsum.photos/seed/prod20/400/300',
  },
  {
    id: 21,
    titulo: 'AirPods Pro 2ª generación',
    descripcion: 'AirPods Pro segunda generación. Con estuche carga MagSafe. Autonomía perfecta.',
    precio: 170,
    estado: 'como_nuevo',
    fecha_publicacion: '2026-04-01',
    categoria_id: 1,
    num_visualizaciones: 143,
    envio_disponible: true,
    lugar_recogida: 'Murcia capital',
    vendedor_id: 2,
    imagen: 'https://picsum.photos/seed/prod21/400/300',
  },
  {
    id: 22,
    titulo: 'Tablet Samsung Galaxy Tab S8',
    descripcion: 'Galaxy Tab S8 128GB WiFi. Con funda Book Cover original. Sin S Pen.',
    precio: 390,
    estado: 'buen_estado',
    fecha_publicacion: '2026-04-02',
    categoria_id: 1,
    num_visualizaciones: 76,
    envio_disponible: true,
    lugar_recogida: 'Cartagena',
    vendedor_id: 3,
    imagen: 'https://picsum.photos/seed/prod22/400/300',
  },
  {
    id: 23,
    titulo: 'Impresora HP LaserJet Pro',
    descripcion: 'Impresora láser HP LaserJet Pro M404dn. Con tóner a mitad. Para piezas o reparar.',
    precio: 30,
    estado: 'para_piezas_o_reparar',
    fecha_publicacion: '2026-04-03',
    categoria_id: 8,
    num_visualizaciones: 22,
    envio_disponible: false,
    lugar_recogida: 'Murcia capital',
    vendedor_id: 2,
    imagen: 'https://picsum.photos/seed/prod23/400/300',
  },
  {
    id: 24,
    titulo: 'Cámara Sony Alpha A6400',
    descripcion: 'Sony A6400 con objetivo 16-50mm kit. 5000 disparos. Sin arañazos en lente.',
    precio: 680,
    estado: 'como_nuevo',
    fecha_publicacion: '2026-04-04',
    categoria_id: 1,
    num_visualizaciones: 230,
    envio_disponible: true,
    lugar_recogida: 'Murcia capital',
    vendedor_id: 3,
    imagen: 'https://picsum.photos/seed/prod24/400/300',
  },
  {
    id: 25,
    titulo: 'Silla gaming Secretlab Titan',
    descripcion: 'Secretlab Titan 2022 talla M. Color negro/rojo. Muy buen estado, sin desgaste.',
    precio: 260,
    estado: 'buen_estado',
    fecha_publicacion: '2026-04-05',
    categoria_id: 8,
    num_visualizaciones: 88,
    envio_disponible: false,
    lugar_recogida: 'Murcia capital',
    vendedor_id: 2,
    imagen: 'https://picsum.photos/seed/prod25/400/300',
  },
  {
    id: 26,
    titulo: 'Olla programable Instant Pot Duo',
    descripcion: 'Instant Pot Duo 7 en 1, 6 litros. Usada 10 veces aprox. Con recetario.',
    precio: 48,
    estado: 'como_nuevo',
    fecha_publicacion: '2026-04-06',
    categoria_id: 3,
    num_visualizaciones: 35,
    envio_disponible: true,
    lugar_recogida: 'Lorca',
    vendedor_id: 3,
    imagen: 'https://picsum.photos/seed/prod26/400/300',
  },
  {
    id: 27,
    titulo: 'Snowboard Burton Custom 158',
    descripcion: 'Burton Custom X 158cm. 3 temporadas de uso. Cantos en buen estado.',
    precio: 290,
    estado: 'buen_estado',
    fecha_publicacion: '2026-04-07',
    categoria_id: 4,
    num_visualizaciones: 51,
    envio_disponible: false,
    lugar_recogida: 'Murcia capital',
    vendedor_id: 2,
    imagen: 'https://picsum.photos/seed/prod27/400/300',
  },
  {
    id: 28,
    titulo: 'Nintendo Switch OLED blanca',
    descripcion: 'Nintendo Switch OLED edición blanca. Con 3 juegos y Joy-Con en perfecto estado.',
    precio: 270,
    estado: 'como_nuevo',
    fecha_publicacion: '2026-04-08',
    categoria_id: 6,
    num_visualizaciones: 312,
    envio_disponible: true,
    lugar_recogida: 'Cartagena',
    vendedor_id: 3,
    imagen: 'https://picsum.photos/seed/prod28/400/300',
  },
  {
    id: 29,
    titulo: 'Bicicleta eléctrica Orbea Gain',
    descripcion: 'Orbea Gain M30 2021. Batería 36V 6Ah. 1200km. Revisión completa hace 2 meses.',
    precio: 1800,
    estado: 'buen_estado',
    fecha_publicacion: '2026-04-09',
    categoria_id: 7,
    num_visualizaciones: 267,
    envio_disponible: false,
    lugar_recogida: 'Murcia capital',
    vendedor_id: 2,
    imagen: 'https://picsum.photos/seed/prod29/400/300',
  },
  {
    id: 30,
    titulo: 'Auriculares Sony WH-1000XM5',
    descripcion: 'Sony WH-1000XM5 negros. Cancelación de ruido excelente. Con funda y cable USB-C.',
    precio: 220,
    estado: 'nuevo',
    fecha_publicacion: '2026-04-10',
    categoria_id: 1,
    num_visualizaciones: 189,
    envio_disponible: true,
    lugar_recogida: 'Murcia capital',
    vendedor_id: 3,
    imagen: 'https://picsum.photos/seed/prod30/400/300',
  },
];

// estado: solicitada | aceptada | rechazada | completada
export const VENTAS = [
  {
    id: 1,
    producto_id: 7,
    comprador_id: 3,
    vendedor_id: 2,
    fecha_solicitud: '2026-03-20',
    estado: 'completada',
  },
  {
    id: 2,
    producto_id: 15,
    comprador_id: 3,
    vendedor_id: 2,
    fecha_solicitud: '2026-03-25',
    estado: 'completada',
  },
  {
    id: 3,
    producto_id: 16,
    comprador_id: 2,
    vendedor_id: 3,
    fecha_solicitud: '2026-03-28',
    estado: 'aceptada',
  },
  {
    id: 4,
    producto_id: 22,
    comprador_id: 2,
    vendedor_id: 3,
    fecha_solicitud: '2026-04-05',
    estado: 'solicitada',
  },
  {
    id: 5,
    producto_id: 10,
    comprador_id: 2,
    vendedor_id: 3,
    fecha_solicitud: '2026-04-10',
    estado: 'solicitada',
  },
  {
    id: 6,
    producto_id: 6,
    comprador_id: 2,
    vendedor_id: 3,
    fecha_solicitud: '2026-04-12',
    estado: 'rechazada',
  },
];
