export const CATEGORIAS = [
  { id: 1, nombre: 'Electrónica' },
  { id: 2, nombre: 'Ropa y Moda' },
  { id: 3, nombre: 'Hogar y Jardín' },
  { id: 4, nombre: 'Deportes' },
  { id: 5, nombre: 'Libros y Música' },
  { id: 6, nombre: 'Juguetes y Bebé' },
  { id: 7, nombre: 'Vehículos' },
  { id: 8, nombre: 'Informática' },
];

export const PRODUCTOS = [
  {
    id: 1,
    titulo: 'iPhone 13 128GB Azul',
    descripcion: 'iPhone 13 en perfecto estado. Batería al 92%. Incluye cargador original y funda.',
    precio: 550,
    estado: 'como_nuevo',
    fecha_publicacion: '2026-03-01',
    categoria_id: 1,
    num_visualizaciones: 142,
    envio_disponible: true,
    lugar_recogida: 'Murcia capital',
    vendedor_id: 2,
    imagen: 'https://picsum.photos/seed/prod1/400/300',
  },
  {
    id: 2,
    titulo: 'Samsung Galaxy S22 Negro',
    descripcion: 'Galaxy S22 con 256GB de almacenamiento. Algunas marcas en la pantalla, funciona perfectamente.',
    precio: 380,
    estado: 'buen_estado',
    fecha_publicacion: '2026-03-05',
    categoria_id: 1,
    num_visualizaciones: 89,
    envio_disponible: true,
    lugar_recogida: 'Cartagena',
    vendedor_id: 3,
    imagen: 'https://picsum.photos/seed/prod2/400/300',
  },
  {
    id: 3,
    titulo: 'MacBook Pro 14" M1 Pro',
    descripcion: 'MacBook Pro 2021 con chip M1 Pro, 16GB RAM, 512GB SSD. Impecable, sin arañazos.',
    precio: 1400,
    estado: 'como_nuevo',
    fecha_publicacion: '2026-03-08',
    categoria_id: 8,
    num_visualizaciones: 210,
    envio_disponible: false,
    lugar_recogida: 'Murcia capital',
    vendedor_id: 2,
    imagen: 'https://picsum.photos/seed/prod3/400/300',
  },
  {
    id: 4,
    titulo: 'Teclado mecánico Keychron K2',
    descripcion: 'Teclado mecánico inalámbrico con switches Brown. Layout TKL. Incluye bolsa de transporte.',
    precio: 75,
    estado: 'buen_estado',
    fecha_publicacion: '2026-03-10',
    categoria_id: 8,
    num_visualizaciones: 55,
    envio_disponible: true,
    lugar_recogida: 'Lorca',
    vendedor_id: 3,
    imagen: 'https://picsum.photos/seed/prod4/400/300',
  },
  {
    id: 5,
    titulo: 'Monitor LG 27" 4K',
    descripcion: 'Monitor LG 27UK850. Panel IPS 4K, USB-C. Un píxel muerto en esquina inferior.',
    precio: 220,
    estado: 'aceptable',
    fecha_publicacion: '2026-03-12',
    categoria_id: 8,
    num_visualizaciones: 98,
    envio_disponible: false,
    lugar_recogida: 'Murcia capital',
    vendedor_id: 2,
    imagen: 'https://picsum.photos/seed/prod5/400/300',
  }
];

export const USUARIOS_MOCK = [
  {
    id: 1,
    nombre: 'Emilio',
    apellidos: 'González Fernández-Piqueras',
    email: 'emilio@segundum.es',
    num_compras: 3,
    num_ventas: 1,
  },
  {
    id: 2,
    nombre: 'Manuel',
    apellidos: 'Chica Piñera',
    email: 'manuel@segundum.es',
    num_compras: 1,
    num_ventas: 5,
  },
  {
    id: 3,
    nombre: 'Laura',
    apellidos: 'Martínez Ruiz',
    email: 'laura@segundum.es',
    num_compras: 0,
    num_ventas: 2,
  },
];

export const VENTAS_MOCK = [
  {
    id: 1,
    producto: 'iPhone 13 128GB Azul',
    precio: 550,
    comprador_id: 1,
    comprador: 'Emilio González',
    vendedor_id: 2,
    vendedor: 'Manuel Chica',
    fecha: '2026-03-15',
  },
  {
    id: 2,
    producto: 'MacBook Pro 14" M1 Pro',
    precio: 1400,
    comprador_id: 2,
    comprador: 'Manuel Chica',
    vendedor_id: 1,
    vendedor: 'Emilio González',
    fecha: '2026-04-02',
  },
  {
    id: 3,
    producto: 'Teclado mecánico Keychron K2',
    precio: 75,
    comprador_id: 1,
    comprador: 'Emilio González',
    vendedor_id: 3,
    vendedor: 'Laura Martínez',
    fecha: '2026-05-10',
  },
];
