server.port=8090
spring.application.name=pasarela

zuul.sensitiveHeaders=

zuul.routes.usuarios.path = /usuarios/**
zuul.routes.usuarios.url = http://localhost:8080/api/usuarios

zuul.routes.productos.path = /productos/**
zuul.routes.productos.url = http://localhost:8081/api/productos

zuul.routes.categorias.path = /categorias/**
zuul.routes.categorias.url = http://localhost:8081/api/categorias

zuul.routes.compraventas.path = /compraventas/**
zuul.routes.compraventas.url = http://localhost:8082/api/compraventas

jwt.secret=***REMOVED***
jwt.expiration-seconds=3600
jwt.cookie-name=jwt

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
