server.port=8090
spring.application.name=pasarela

zuul.sensitiveHeaders=

zuul.routes.usuarios.path = /usuarios/**
zuul.routes.usuarios.url = http://localhost:8080/api/usuarios

zuul.routes.productos.path = /productos/**
zuul.routes.productos.url = http://localhost:8081/api/productos

zuul.routes.compraventas.path = /compraventas/**
zuul.routes.compraventas.url = http://localhost:8082/api/compraventas